# Autogenerated wrapper script for argon2_jll for aarch64-apple-darwin
export libargon2

JLLWrappers.@generate_wrapper_header("argon2")
JLLWrappers.@declare_library_product(libargon2, "@rpath/libargon2.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libargon2,
        "lib/libargon2.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
